name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # Make sure commit messages follow the conventional commits convention:
  # https://www.conventionalcommits.org
  commitlint:
    name: Lint commit messages
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@b948419dd99f3fd78a6548d48f94e3df7f6bf3ed # v6.2.1

  test:
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.13"
        os:
          - ubuntu-24.04
          - macos-latest
    runs-on: ${{ matrix.os }}
    env:
      OS: ${{ matrix.os }}
      PYTHON_VERSION: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: ${{ matrix.python-version }}
      - uses: snok/install-poetry@a783c322200f0519c7926aa6faa857c4e23e9263 # v1.4.2
      - name: Install dependencies
        run: poetry install
        shell: bash
      - name: Test with PyTest
        run: poetry run pytest --cov-report=xml
        shell: bash
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: OS, PYTHON_VERSION
          verbose: true

  release:
    runs-on: ubuntu-24.04
    environment:
      name: release
      url: https://pypi.org/project/aiolifx-themes/
    if: github.ref == 'refs/heads/main'
    concurrency: release
    permissions:
      id-token: write
      contents: write
    needs:
      - test
      - commitlint

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: "3.14"

      - name: Install Poetry
        uses: snok/install-poetry@a783c322200f0519c7926aa6faa857c4e23e9263 # v1.4.2

      - name: Install dependencies using Poetry
        run: poetry install
        shell: bash

      - name: Run Python Semantic Release
        id: release
        uses: python-semantic-release/python-semantic-release@350c48fcb3ffcdfd2e0a235206bc2ecea6b69df0 # v10.5.3
        with:
          github_token: ${{ secrets.GH_TOKEN }}

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # release/v1
        if: steps.release.outputs.released == 'true'
        with:
          verbose: true
          print-hash: true

      - name: Publish package distributions to GitHub Releases
        uses: python-semantic-release/publish-action@310a9983a0ae878b29f3aac778d7c77c1db27378 # main
        if: steps.release.outputs.released == 'true'
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          tag: ${{ steps.release.outputs.tag }}
